### ISSUE TITLE
URL encoding

### ISSUE THREAD

**Issue by CraigChamberlain** [csMACnz/coveralls.net#101]
Happy to look into taking this on if its a feature of interest.

I had a directory "C#" that used a special character '#'.  This was uploaded to coveralls.io and the path was shipped directly to coveralls as C#.  However coveralls was expecting an escaped character and the links formed from this path produced 404s on the website.

For example 
https://coveralls.io/builds/xxxx/source?filename=/C#/sampleProject/Ranges.cs -> 404
https://coveralls.io/builds/xxxx/source?filename=/C%23/sampleProject/Ranges.cs -> link to github file and correct display.

**Comment by CraigChamberlain** [comment]
There is the obvious answer to not include special characters in your directory structure.  This was my immediate solution.

I've been looking through the solution to see where serialisation is taking place, to see if I can spot a good place to url encode paths.

This is where the JSON payload is dispatched.
https://github.com/csMACnz/coveralls.net/blob/bcc9f18a4641621219427e399ea2dbf854f43cfb/src/csmacnz.Coveralls/Adapters/CoverallsService.cs#L17

Each supported coverage file has it's own parser so it would be ideal to have it one step above the parsers so it doesn't need to be implemented in too many files.
For example in the constructor of FileCoverageData?
https://github.com/csMACnz/coveralls.net/blob/bcc9f18a4641621219427e399ea2dbf854f43cfb/src/csmacnz.Coveralls/Data/FileCoverageData.cs#L20
Or the getter of FileCoverageData.FullPath?
https://github.com/csMACnz/coveralls.net/blob/bcc9f18a4641621219427e399ea2dbf854f43cfb/src/csmacnz.Coveralls/Data/FileCoverageData.cs#L25

**Comment by csMACnz** [comment]
I had been doing some work in develop to get to dotnet 3.1 whenever i had spare time, but if you want to contribute this to the 2.0.0 RC branch i can use it as motivation to make that a release version...

If you've got time to do the dev I will do my best to help it along.

**Comment by CraigChamberlain** [comment]
I would love to help if I can.  I'm not a regular contributor but will try my best.

Fork the master and make a patch branch?

Did I get the right end of the stick finding places to do the escape?  I would have started looking at encoding the getter on FileCoverageData.FullPath

Probably a way to do with a data annotation depending on the serialiser?

**Comment by csMACnz** [comment]
If you base your patch branch off of the https://github.com/csMACnz/coveralls.net/tree/release-2.0.0 branch? There is probably too much divergence between master and develop otherwise. I plan to switch to trunk-based soon to make things simpler...

**Comment by CraigChamberlain** [comment]
Great, this seems to support my idea:

https://stackoverflow.com/questions/46180408/configure-json-net-to-url-encode-certain-field

**Comment by CraigChamberlain** [comment]
https://github.com/csMACnz/coveralls.net/pull/102

**Comment by CraigChamberlain** [comment]
By the way, love the Beefeater library.  DUs of Result and Option are of the best features of f#, really miss it  in C#

**Comment by CraigChamberlain** [comment]
This looks like the responsibility of coveralls.io

https://docs.coveralls.io/api-reference
 See: source_file -> name


If only the file path is submitted to the app then it should remain unencoded.  When you navigate the file tree in the Ui it should have unescaped chars and when you hit file link to the source, the encoding should occur there.
