### ISSUE TITLE
Unable to install v3.0.0 via dotnet tool

### ISSUE THREAD

**Issue by TheFriendlyCoder** [csMACnz/coveralls.net#106]
The docs indicate that, when running on the .NET framework v5 you need to install the latest version of coveralls.net (v3.0.0) using the dotnet tools installer (ie: **dotnet tool install coveralls.net --version 3.0.0**). Based on my ad-hoc testing, this does not work. You seem to need to append a custom package source for this to work (ie: **dotnet tool install coveralls.net --version 3.0.0 --add-source https://ci.appveyor.com/nuget/coveralls-net-t37a9a9unhwk**). Similarly, when installing this version as a local tool, you need to include the additional package source when restoring your tools on a new checking, as in **dotnet tool restore --add-source https://ci.appveyor.com/nuget/coveralls-net-t37a9a9unhwk**.

I am relatively new to dotnet so perhaps I am doing something wrong here. If so feel free to clarify.

**Comment by csMACnz** [comment]
Sorry about that, I got very distracted through my southern hemisphere summer and didn't complete the release process. I created the tag but hadn't doubled back to fix the automations. I've manually run the release notes and nuget.org (still indexing as i write this...) So it should be good to go without the need of the add source.

I do need to update the appveyor source docs to make is easier to get pre-release versions though, thanks for reminding me of that 😅 

Hopefully by the time you read this it will no longer be an issue 👍
