### ISSUE TITLE
Support Net6

### ISSUE THREAD

**Issue by mristin** [csMACnz/coveralls.net#109]
Hi @csMACnz,
Thanks a lot for your tool! I use it across multiple repositories to upload the test coverage.

We started migrating some of them to Net6 since it is a LTS version. This forces us to install Net5 in all of our continuous integrations just to run coveralls.net. 

Have you perhaps considered migrating coveralls.net to Net6 as well?

**Comment by csMACnz** [comment]
Certainly! I think I even had a local Dev branch for that already... I hope I can get that done soon.

**Comment by csMACnz** [comment]
Turns out I was thinking of the .Net 5.0 work I did last year. I've made the jump to c# 10 and .Net 6.0 with a version 4.0.0 to be published soon

**Comment by csMACnz** [comment]
OK 🤞 I've deployed version 4.0.0 now to nuget.org. Let me know if you have any issues or bugs to report. 🙈

**Comment by mristin** [comment]
Thanks, @csMACnz! Just to confirm: `coveralls.net` works just fine in our CI pipelines!
