### ISSUE TITLE
Handle Pull Request Builds

### ISSUE THREAD

**Issue by csMACnz** [csMACnz/coveralls.net#38]
As a repository owner, I want to see coveralls.net results from Pull Request builds so that I can check coverage stats have not decreased from a PR change.

Pull Requests do not currently build using the same calling code from AppVeyor. The application might need to be away of pull request builds to publish correctly.

**Comment by Sharparam** [comment]
It would be nice if there was an option to manually supply the pull request ID.

It seems the basic changes needed is to add the API field to [CoverallData.cs](https://github.com/csMACnz/coveralls.net/blob/master/src/csmacnz.Coveralls/CoverallData.cs) as well as add a command-line option to supply that value.

Between this project and the other [coveralls for .net](https://github.com/coveralls-net/coveralls.net), it seems this one has way more options to supply on the command-line while the other one focuses on strictly integrating into pre-defined CI solutions.

([Coveralls API reference mentioning `service_pull_request` field](https://coveralls.zendesk.com/hc/en-us/articles/201350799-API-Reference))

**Comment by csMACnz** [comment]
From memory, pull request builds (on appveyor at least) don't get access to secure variables (such as the coveralls.io api token). This makes sense from a security point of view, since anyone could open a pr with malicious code that exposes all the secure settings. 

Because of this the option is either don't publish PR results, or expose your key publicly. And because of this i haven't had much motivation to add this functionality yet. 

Thanks for your feedback though, I will try to add this setting at some point if your still interested despite the security risks of PRs :)

**Comment by Sharparam** [comment]
Yep, back when we tried out appveyor for CI we had the "issue" of the coveralls token not expanding. We're currently on TeamCity which has an option for secure variables as well, though I'm not sure if it masks them when detected in build output. Might be worth testing. I believe Jenkins will mask secure variables if they are detected in build output (if the option is enabled).

**Comment by csMACnz** [comment]
Released in version 1.0.0 as above
