### ISSUE TITLE
Failed to upload to coveralls - AppVeyor

### ISSUE THREAD

**Issue by lfreneda** [csMACnz/coveralls.net#42]
Getting "Failed to upload to coveralls" error when calling csmacnz.Coveralls.exe.

What should I check?

**Comment by lfreneda** [comment]
Getting the following response from api 

HTTP/1.1 500 Internal Server Error
Server: cloudflare-nginx
Date: Fri, 12 Jun 2015 18:36:00 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d47f63e96e418dd5b35aab78d144138ed1434134160; expires=Sat, 11-Jun-16 18:36:00 GMT; path=/; domain=.coveralls.io; HttpOnly
Status: 500 Internal Server Error
X-UA-Compatible: IE=Edge,chrome=1
Cache-Control: no-cache
Set-Cookie: request_method=POST; path=/
X-Request-Id: a81126ba350d2e91ca63f0697496f57e
X-Runtime: 0.470157
X-Rack-Cache: invalidate, pass
X-Powered-By: Phusion Passenger 4.0.47
Set-Cookie: LSW_WEB="LSW_WEB2"; path=/
CF-RAY: 1f57a8a2fb5b07bb-MIA

3b
{"message":"Build processing error.","error":true,"url":""}
0

**Comment by csMACnz** [comment]
Looking into it. It might be transient, or something in their api might have changed.

**Comment by lfreneda** [comment]
The same error is ocurring with the project sample

https://github.com/csMACnz/Coveralls.net-Samples/tree/nunit-opencover-appveyor

(I don't know if helps)

**Comment by lfreneda** [comment]
I tried wtih another combination of tools xunit + opencover + appveyor, it works for commits on master, but PR is not working ç___ç

commit on master:
https://ci.appveyor.com/project/lfreneda/coveralls-testing/build/1.0.5

pull request:
https://ci.appveyor.com/project/lfreneda/coveralls-testing/build/1.0.9

**Comment by csMACnz** [comment]
Looks like the original error was a temporary one on coveralls.io.  All my builds failed a few hours ago but all run green now when i re-run them.

Pull Requests are a special case:  AppVeyor environment variables are not available to your script when it is run over a PR. This is a security thing. stops someone exposing your keys with a malicious PR script. I've started making this conditional in my build scripts now:
https://github.com/csMACnz/coveralls.net/blob/develop/build.tasks.ps1#L148


(during a PR, your script becomes "...opencoverCoverage.xml --repoToken  --commitId $env:APPVEYOR_REPO_COMMIT..." which is seen as invalid syntax, so the Usage message gets printed. I think if you put $env:COVERALLS_REPO_TOKEN in quotes you see a clearer message)

**Comment by csMACnz** [comment]
Looks like this is a Coveralls issue.
https://github.com/lemurheavy/coveralls-public/issues/547

It went away but is now back again.

**Comment by lfreneda** [comment]
Hmmmmn, is that for all languages, right?

Weirdo :S
