### ISSUE TITLE
Unable to Upload to Coveralls.io from AppVeyor

### ISSUE THREAD

**Issue by tsutomi** [csMACnz/coveralls.net#47]
Hi,

Since days I've been trying to upload the results of coverage from opencover to coveralls.io using coveralls.net.
I've tried several configurations, and finally I ended it to this 

    $opencoverPath = "user"
     If ($platform -eq "x86") {
           $opencoverPath = "Path32"
       } ElseIf ($platform -eq "x64") {
           $opencoverPath = "Path64"
       }

         Write-Host "Producing Coverage"

        $opencover = (Resolve-Path "src/packages/OpenCover.*/tools/OpenCover.Console.exe").ToString()
        $nunit = (Resolve-Path "src/packages/NUnit.Runners.*/tools/$nunitapp").ToString()
        & $opencover -register:$opecoverPath -target:"$nunit" -targetargs:"$root\src\deveeldb-nunit\bin\$platform\$conf\deveeldb-nunit.dll /noshadow /domain:single" -output:"$root\dist\$platform\coverage.xml"

         Write-Host "Sending Coverage results to Coveralls.io"

         $coveralls = (Resolve-Path "src/packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
         & $coveralls --opencover -i "$root\dist\$platform\coverage.xml" --repoToken $COVERALLS_REPO_TOKEN --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor

While the other configurations were giving me errors when trying to invoke coveralls.net, this one only prints out the usage, such as if the parameters passed were wrong.

Can you please verify if anything there is wrong?

**Comment by csMACnz** [comment]
It looks like possibly the variable `$COVERALLS_REPO_TOKEN` is not set.  To verify this this the problem, use:

```
& $coveralls --opencover -i "$root\dist\$platform\coverage.xml" --repoToken "$COVERALLS_REPO_TOKEN" --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
```
(note the quotes around the token variable)

It should give you a better error message. Currently, if it is missing you would be trying to call it with

```
& coveralls.exe --opencover -i "mypath\coverage.xml" --repoToken  --jobId 12345 --serviceName appveyor
```
And that **Is** invalid syntax, (because there is no repoToken argument) and would cause the error you are seeing.

**Comment by tsutomi** [comment]
Actually, I found out the error was the fact you must invoke the `$COVERALLS_REPO_TOKEN` variable with the `$env:` prefix: after I did, all was fine
