### ISSUE TITLE
Support for Chutzpah coverage (java script)

### ISSUE THREAD

**Issue by HarelM** [csMACnz/coveralls.net#56]
I'm using visual studio to write my c# code, I also write my web application code with typescript and Chutzpah.
Is it possible to add support for Chutzpah coverage report as well? I think it can write a few output format for coverage as far as I can understand from their wiki:
https://github.com/mmanela/chutzpah/wiki/command-line-options

**Comment by csMACnz** [comment]
I could, however the main focus of this app is for .net code coverage.

Having said that, many dotnet apps have javascript components and it doesn't seem like a big deal to add it in.

I'll add it to the backlog of things to do.

**Comment by HarelM** [comment]
I'm a C# developer, but when it comes to web you can't stay purely in C#.
Here's an example of the output in json format, I think it shouldn't be hard, I'll see if I manage to make it work myself and see if I can send a PR.
[chutzpah-results-coverage.txt](https://github.com/csMACnz/coveralls.net/files/418756/chutzpah-results-coverage.txt)
BTW, it is possible to send multiple files?

**Comment by csMACnz** [comment]
There are a lot of features on the api, we should be able to make anything work :)

**Comment by HarelM** [comment]
The API probably supports it, but the current execution is in the command line in per file, so it might change the way the command line will work.
I made some progress with the chutzpah parser, hope to finish it soon.

**Comment by csMACnz** [comment]
I just realised I have a release to push to master. I'll push that through now, I hope it doesn't disrupt you too much.

**Comment by HarelM** [comment]
Finished, to which branch should I do the pull request? master?

**Comment by HarelM** [comment]
See pull request #58.
Assuming I made it work correct the question now is how to send multiple files.
Judging from what I gather there's a need to merge all the files and send a single request to coveralls.
BTW, is this repository somehow related to coveralls-net/coveralls.net?

**Comment by csMACnz** [comment]
Sorry, you might need to rebase your changes onto master again, I had a pending release branch that wasn't merged in.

I'll have to see what i can do, the api allows you to submit multiple reports (if you have multiple runs, which you will have at least two, a C# and a javascript) but i still need to add support for that. This is a good chance to do so.  For the single runner, do you get a single report that has all the results?

No relation to coveralls-net/coveralls.net, other then we both started writing them over the same summer and released them at about the same time independently. From what I gather, his has more coverage over itself with tests, but mine supports more formats. (Though he has twice as many total downloads as me.)

**Comment by csMACnz** [comment]
And I just realised that you should probably target develop rather than master, too

**Comment by HarelM** [comment]
I'll see what I can do tonight, so your saying I should send my pull request to develop branch instead of stable? I would probably need to develop it on this branch I guess.
I'll take care of it.

**Comment by HarelM** [comment]
Sorry, forgot about the develop branch, do you want me to create another pull request?
