### ISSUE TITLE
Support Lcov format

### ISSUE THREAD

**Issue by HarelM** [csMACnz/coveralls.net#64]
here is an example of this format, I saw it when looking into possible alternatives, I think it's in use in some cases, chutzpah is one of them and I think there are more, I'll see if I can send a pull request to add it.
[coverage-chutzpah.txt](https://github.com/csMACnz/coveralls.net/files/428358/coverage-chutzpah.txt)

**Comment by csMACnz** [comment]
in develop, pending testing, it will be in the next release.
