### ISSUE TITLE
travis + monocov + public repo

### ISSUE THREAD

**Issue by njasm** [csMACnz/coveralls.net#69]
command line syntax not clear:
installing version 0.6.0
command executed : 
```
mono ./testrunner/coveralls.net.0.6.0/tools/csmacnz.Coveralls.exe --monocov -i ./monocovCoverage --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName "travis-ci"  --useRelativePaths

No token found in Environment Variable 'COVERALLS_REPO_TOKEN'.
```
how do you go with a public repo without leaking the coveralls token?
Apparently Coveralls.io does not need repo token when submitting coverage for public repositories. reference : lemurheavy/coveralls-public#208

**Comment by csMACnz** [comment]
Interesting, I wasn't aware of this. Ill do some investigation to see what I need to change to make this work. Hopefully it is as simple as not sending any token but I suspect might not be.

**Comment by csMACnz** [comment]
So from what I've read this seems to not needed. Ill update the validation and test if it works as expected.  For now you can use a private environment variable to set the token on travis ci settings to make this work. (this is a private hidden environment variable, not in the repo)

**Comment by njasm** [comment]
@csMACnz cool thanks for the heads up on the private environment var in travis. 
now I'm able to bypasse this issue. now I just need to find why monocov is exporting an empty xml file.. 

thanks for the help.

**Comment by csMACnz** [comment]
If it helps, I have 2 example repositories that are working (nunit or xunit with travis and monocov).

https://github.com/csMACnz/Coveralls.net-Samples/tree/nunit-monocov-travisci
https://github.com/csMACnz/Coveralls.net-Samples/tree/xunit-monocov-travisci

**Comment by njasm** [comment]
@csMACnz cool thanks, but I've ended up using nuinit, openCover in appveyor.
monocov apparently does not work anymore with latest versions of mono.

thanks for the help.

**Comment by csMACnz** [comment]
Perfect. I knew monocov was out of support so not surprised.

I am still holding out for a working Coverage solution on Linux myself. Once it exists, I will make sure i put together a sample of how it works.
