### ISSUE TITLE
Pull request builds only work on 0.7.0.beta.0001 and not on default nuget package

### ISSUE THREAD

**Issue by stefanks** [csMACnz/coveralls.net#70]
So something got lost along the way. I have to use that beta version to get coveralls feedback on pull requests.

**Comment by csMACnz** [comment]
Sorry, I made some fixes for PRs that a few people have been testing/using that I haven't had a chance to verify myself, so it hadn't made it to stable yet. I hope to find some time to do a release build, but in the meantime yes the beta should be fine, and just let me know if you find any issues.

Thanks!

**Comment by csMACnz** [comment]
I am building a release candidate 0.8.0 which I think will help with your issue?

If I have misunderstood, could you please provide more details of the problem. thanks

**Comment by csMACnz** [comment]
I'm migrating to dotnet core, so this will probably just go away as a problem when i get that out, if it still is.

**Comment by stefanks** [comment]
alright!

**Comment by csMACnz** [comment]
This is working and tested in the next beta release (1.0.0-beta.3) and will be in the 1.0.0 release as soon at dotnet 2.1 goes to RTM.  Note that this will be a dotnet tool package as off 1.0.0.

Example repo running on the rc1 of 2.1 is here:

https://github.com/csMACnz/Coveralls.net-Samples/pull/7

**Comment by csMACnz** [comment]
Version 1.0.0 is released and solves this now for stable. Released as dotnet cli 2.1 tool.

There are some gotchas, documented here:
https://github.com/csMACnz/coveralls.net/wiki/Pull-Requests
