### ISSUE TITLE
coveralls + travis + docker

### ISSUE THREAD

**Issue by condemil** [csMACnz/coveralls.net#88]
I am using docker container with travis to test and generate coverage report. As I am aware (based on my experience with other languages) when you use coveralls with travis on public repositories you don't need to specify any additional tokens, however with coveralls.net I got this:

```
No token found in Environment Variable 'COVERALLS_REPO_TOKEN'.
coverall failed!
```

I passed the following environment variables to container:

```
ARG CI
ARG TRAVIS
ARG TRAVIS_BRANCH
ARG TRAVIS_COMMIT
ARG TRAVIS_JOB_ID
ARG TRAVIS_JOB_NUMBER
ARG TRAVIS_OS_NAME
ARG TRAVIS_PULL_REQUEST
ARG TRAVIS_PULL_REQUEST_SHA
ARG TRAVIS_REPO_SLUG
ARG TRAVIS_TAG
```

**Comment by csMACnz** [comment]
As suggested, you will also need to pass in the `COVERALLS_REPO_TOKEN` environment variable as well. 

If you link to a public repository and build where you are having trouble with I could take a closer look, although I suspect this to be the problem.

**Comment by condemil** [comment]
Yes you can add `COVERALLS_REPO_TOKEN` in travis settings by copy-pasting it from coveralls, but this will be way-around and not the way how other coveralls tools do that.

I took as an an example one implementation, here you have:

1. [Get](https://github.com/coveralls-clients/coveralls-python/blob/c0e422133945007ae96d496dfb8217d148289ff0/coveralls/api.py#L90-L92) service_name as `travis-ci` and data from `TRAVIS_PULL_REQUEST ` and `TRAVIS_JOB_ID` environment variables
2. Add it to data structure with names `service_name `, `service_job_id ` and `service_pull_request`
3. POST it to `/api/v1/jobs` together with other data that you already sending

You can also find `service_name `, `service_job_id ` and `service_pull_request` for appveyor, buildkite, circle ci and jenkins in the [same file](https://github.com/coveralls-clients/coveralls-python/blob/c0e422133945007ae96d496dfb8217d148289ff0/coveralls/api.py#L71-L87).

**Comment by csMACnz** [comment]
Apologies for the confusion.  I have added the travis provider into the next release version code, but have not released it yet. Until this is released, all settings will need to be done explicitly.

The example of how to do this for now unfortunately is to specify all the command-line arguments against the tool, and then also specify all the environment variables used to docker as well.

My hope is that soon i can work on a further release including the Travis support automatically, and then you will only need to specify everything in docker once.

**Comment by csMACnz** [comment]
I see the linked PR was a success so am closing this Issue.
