### ISSUE TITLE
dotnet core 2.2

### ISSUE THREAD

**Issue by pnahtanoj** [csMACnz/coveralls.net#89]
We have a core 2.2 project that could really benefit from this package.

**Comment by csMACnz** [comment]
Any more detail you can add?  Is it just the target runtime that is the problem?  This is a tool, so shouldn't need to match your target version. To publish your coverage results.

Let me know if there is something more to this.

Thanks for your feedback! 😁

**Comment by pnahtanoj** [comment]
Ha, I wasn't following instructions!  I was trying to dotnet add package, which was complaining about the runtime target.
