### ISSUE TITLE
Question - commands the new way

### ISSUE THREAD

**Issue by DigitalMystery** [csMACnz/coveralls.net#90]
I'm trying to integrate this with Travis CI.  If my project is open source on GitHub what commands do I need to run get the file to Coveralls?  I thought it was automatic, but missing something someplace.  Currently I have this in my scripts section of my Travis.yml which does build the code coverage file locally if run or on Travis:

`- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover`

I was looking at the basic command in the readme, but just not grasping something.

`csmacnz.Coveralls --opencover`

Any help would be much appreciated

**Comment by csMACnz** [comment]
on travis you still need to use all the arguments. The next release will have automatic support for Travis (like appveyor) but the latest stable doesn't have that yet.

**Comment by csMACnz** [comment]
I don't (yet) have a travis coverlet example in samples, but the monocov example does show what i mean about the arguments.

https://github.com/csMACnz/Coveralls.net-Samples/blob/xunit-monocov-travisci/.travis.yml#L32

**Comment by DigitalMystery** [comment]
thank you, I will get back around to that project in a week or two and take a look.  If i have any other questions I will just message back.
