### ISSUE TITLE
appveyor : incompatible frmaework version

### ISSUE THREAD

**Issue by b3b00** [csMACnz/coveralls.net#91]
Hi , working on integratinf coveralls in my appveyor build, I get the following error :

 ```
tools/csmacnz.coveralls.exe : It was not possible to find any compatible framework version
At line:30 char:1
+ tools/csmacnz.coveralls.exe --opencover -i opencoverCoverage.xml --re ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (It was not poss...amework version:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 ```
I reproduced it on my computer and have been able to run it changing framework version in all csproj from netcoreapp1.0 to netcoreapp2.2.
But this is not possible on appveyor. 

IS there any workaround ?

**Comment by b3b00** [comment]
Sorry I was able to solve it : 
I was using
```
dotnet tool install coveralls.net --version 1.0.0-beta0002 --tool-path tools
```
to install the tool.
switching to version 1.0.0 seems to solve the problem

**Comment by csMACnz** [comment]
glad to hear you got this working :)
